<template>
  <el-table
    :data="adData"
    stripe
    style="width: 100%">
    <el-table-column
    prop="orderId"
    label="订单号">
    </el-table-column>
    <el-table-column
    prop="createTime"
    label="创建时间"
    </el-table-column>
    <el-table-column
    prop="currencyType"
    label="币种">
    </el-table-column>
    <el-table-column
    prop="address"
    label="类型">
    </el-table-column>
    <el-table-column
    prop="address"
    label="交易对象">
    </el-table-column>
    <el-table-column
    prop="currencyPrice"
    label="交易价格">
    </el-table-column>
    <el-table-column
    prop="coinAmount"
    label="数量">
    </el-table-column>
    <el-table-column
    prop="address"
    label="金额">
    </el-table-column>
    <el-table-column
    prop="address"
    label="手续费">
    </el-table-column>
    <el-table-column
    prop="referenceNumber"
    label="参考号">
    </el-table-column>
</el-table>
</template>

<script>
export default {
  props: ['adData'],
}
</script>
